<Project>
    <PropertyGroup>
        <Authors>Cosmin Crețu</Authors>
        <Company>Blossom</Company>
        <Copyright>Copyright (c) 2023-2026 Cosmin Crețu</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/cretucosmin3/Blossom</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/cretucosmin3/Blossom</PackageProjectUrl>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94" PrivateAssets="all" />
    </ItemGroup>
</Project>

